version: '3.8'

services:
  postgres:
    container_name: neurocoperacao-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: neuro
      POSTGRES_DB: nest-neuro
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres